package de.matzefratze123.exampleaddon;

import org.bukkit.ChatColor;
import org.bukkit.command.CommandSender;

import de.matzefratze123.heavyspleef.addon.AddOnProperties;
import de.matzefratze123.heavyspleef.commands.base.Command;
import de.matzefratze123.heavyspleef.commands.base.CommandContext;
import de.matzefratze123.heavyspleef.commands.base.CommandException;
import de.matzefratze123.heavyspleef.core.HeavySpleef;

/*
 * Every class can be a command class
 */
public class ExampleCommand {
	
	/*
	 * Every command method must be annotated with @Command declaring the commands name,
	 * the usage, a brief description and an optional permission for using the command.
	 * 
	 * The first parameter of a command method is usually an instance of a CommandContext,
	 * optional parameters are the HeavySpleef instance and an instance of your main add-on class
	 */
	@Command(name = "example", usage = "/spleef example", description = "Sends you a nice message!",
			permission = "heavyspleef.player.example", minArgs = 1)
	//@PlayerOnly - Declare this method if you only want players to be able to execute this command
	public void onExampleCommand(CommandContext context, HeavySpleef heavySpleef, ExampleAddon addon) 
			throws CommandException {
		//Gets the sender of this command
		CommandSender sender = context.getSender();
		//Gets the first argument the sender typed in
		String arg = context.getString(0);
		
		//Access to the main add-on class is granted as a parameter
		AddOnProperties properties = addon.getProperties();
		
		sender.sendMessage(ChatColor.GOLD + "You typed in the following word: " + arg);
		sender.sendMessage(ChatColor.GOLD + "This message was generated by the " + properties.getName() + " add-on.");
	}

}
